### CREATE BLOG
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hY2hvQGhvdG1haWwuY29tIiwiaWQiOjIsImlhdCI6MTc0MTQ4NTAzOX0.IjMy1ZR-g49goZtJJeVnHoa6fp8AWNxTREeF3dUjPA4

{
  "author": "Will Smith",
  "url": "www.meninblack.com",
  "title": "The new men in black"
}

# {
#   "author": "Dale Carnegie",
#   "url": "www.carnegiecompany.com",
#   "title": "How to win friends",
#   "likes": "80"
# }

# {
#   "author": "Dr. King",
#   "url": "www.drkingblogs.com",
#   "title": "The new era of slavery",
#   "likes": "2"
# }

### DELETE BLOG
DELETE http://localhost:3001/api/blogs/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hY2hvQGhvdG1haWwuY29tIiwiaWQiOjIsImlhdCI6MTc0MTQ4NTAzOX0.IjMy1ZR-g49goZtJJeVnHoa6fp8AWNxTREeF3dUjPA4

### UPDATE LIKE COUNT
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": "777"
}