### CREATE BLOG
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvYWFzZWNhcyIsImlkIjoxLCJpYXQiOjE3NDE0OTA4NDN9.qp72w98cMICbRB6zaTVQQLkKoNzxZijGOr4c5tBRbmA

{
  "author": "Theo",
  "url": "www.t4.com",
  "title": "React and you."
}

# {
#   "author": "Dale Carnegie",
#   "url": "www.carnegiecompany.com",
#   "title": "How to win friends",
#   "likes": "80"
# }

# {
#   "author": "Dr. King",
#   "url": "www.drkingblogs.com",
#   "title": "The new era of slavery",
#   "likes": "2"
# }

### DELETE BLOG
DELETE http://localhost:3001/api/blogs/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hY2hvQGhvdG1haWwuY29tIiwiaWQiOjIsImlhdCI6MTc0MTQ4NTAzOX0.IjMy1ZR-g49goZtJJeVnHoa6fp8AWNxTREeF3dUjPA4

### UPDATE LIKE COUNT
PUT http://localhost:3001/api/blogs/8
Content-Type: application/json

{
  "likes": "1500"
}